---
theme:  "docs-balsamiq-com"
baseurl:  "http://docsb2b3.balsamiq.com"
languageCode:  "en-us"
title:  "Balsamiq Documentation"
MetaDataFormat:  "yaml"
pluralizeListTitles:  false
Paginate:  "50"
PageSize:  "50"
contentdir:  "content"
layoutdir:  "layouts"
publishdir:  "public"
params:
  balsamiqcomurl: "http://staging.balsamiq.com"

blackfriday:
  plainIdAnchors:  true

taxonomies:
  category:  "categories"
  tag:  "tags"
---
